# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("github.com/openconfig/gnmi/proto/gnmi_ext/gnmi_ext.proto", :syntax => :proto3) do
    add_message "gnmi_ext.Extension" do
      oneof :ext do
        optional :registered_ext, :message, 1, "gnmi_ext.RegisteredExtension"
        optional :master_arbitration, :message, 2, "gnmi_ext.MasterArbitration"
        optional :history, :message, 3, "gnmi_ext.History"
      end
    end
    add_message "gnmi_ext.RegisteredExtension" do
      optional :id, :enum, 1, "gnmi_ext.ExtensionID"
      optional :msg, :bytes, 2
    end
    add_message "gnmi_ext.MasterArbitration" do
      optional :role, :message, 1, "gnmi_ext.Role"
      optional :election_id, :message, 2, "gnmi_ext.Uint128"
    end
    add_message "gnmi_ext.Uint128" do
      optional :high, :uint64, 1
      optional :low, :uint64, 2
    end
    add_message "gnmi_ext.Role" do
      optional :id, :string, 1
    end
    add_message "gnmi_ext.History" do
      oneof :request do
        optional :snapshot_time, :int64, 1
        optional :range, :message, 2, "gnmi_ext.TimeRange"
      end
    end
    add_message "gnmi_ext.TimeRange" do
      optional :start, :int64, 1
      optional :end, :int64, 2
    end
    add_enum "gnmi_ext.ExtensionID" do
      value :EID_UNSET, 0
      value :EID_EXPERIMENTAL, 999
    end
  end
end

module GnmiExt
  Extension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.Extension").msgclass
  RegisteredExtension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.RegisteredExtension").msgclass
  MasterArbitration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.MasterArbitration").msgclass
  Uint128 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.Uint128").msgclass
  Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.Role").msgclass
  History = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.History").msgclass
  TimeRange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.TimeRange").msgclass
  ExtensionID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.ExtensionID").enummodule
end
